Repository UCLALibrary/sinaimanuscripts, pull requests merged in 2023-06, with the labels that each got.

#100 fix: update Illustrations note label to Decoration note
  app/controllers/catalog_controller.rb
  app/views/catalog/work_record--sinai/_decorations_metadata.html.erb
  config/metadata-sinai/decoration_metadata.yml
  config/metadata/physical_description_metadata.yml
  spec/presenters/sinai/decoration_metadata_presenter_spec.rb
  spec/presenters/ursus/physical_description_metadata_presenter_spec.rb
Labels: Fix

#101 fix: APPS-1799 Sinai: "Place of Origin" should not be a facet
  app/controllers/catalog_controller.rb
Labels: In Progress, Fix

#102 ci: add gh workflow for on merge and tag build
  .github/workflows/on-merge.yml
  .github/workflows/tag-build.yml
Labels: feature
